# .travis.yml for Kitura
# See the following URLs for further details
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/

sudo: true

# whitelist
branches:
  only:
    - master
    - develop

notifications:
  slack: ibmswift:RHkwcHYh4kkYVRVzm9nZk5TF

services:
  - docker

before_install:
  - docker login -e $DOCKER_HUB_EMAIL -u $DOCKER_HUB_USERID -p $DOCKER_HUB_PWD
  - docker pull milbuild/kitura-ubuntu:latest

script:
  - echo "About to run docker container to build and test Phoenix for branch '$TRAVIS_BRANCH'."
  - docker run --rm -e PHOENIX_BRANCH=$TRAVIS_BRANCH milbuild/kitura-ubuntu:latest
  - echo "Build and tests completed. See above for status."
