language: c

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libhttp-parser2.1-dev
    - libcurl3
    - libkqueue-dev

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libkqueue-dev
  - sudo apt-get install -y automake
  - sudo apt-get install -y libbsd-dev

before_script:
#  - sudo apt-get update
  #- sudo apt-get install libhttp-parser2.1-dev libcurl3 libpcre3 libhiredis-dev
  
script:
# Upgrade autoconf
  - wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz
  - tar xvfvz autoconf-2.69.tar.gz
  - cd autoconf-2.69
  - ./configure
  - make
  - sudo make install
# Install Swift
  - wget https://swift.org/builds/ubuntu1510/$SWIFT_BUILD/$SWIFT_BUILD-ubuntu15.10.tar.gz
  - tar xzvf $SWIFT_BUILD-ubuntu15.10.tar.gz
  - git clone -b opaque-pointer git://github.com/seabaylea/swift-corelibs-libdispatch
  - cd swift-corelibs-libdispatch
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
