# Travis CI build file for Kitura sample app.
# Kitura runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - develop

notifications:
  slack: ibmswift:RHkwcHYh4kkYVRVzm9nZk5TF

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode7.2
      sudo: required

before_install:
  - git submodule init
  - git submodule update
  - cd Kitura-CI && git checkout $TRAVIS_BRANCH && cd $TRAVIS_BUILD_DIR

script:
  - echo ">> Let's build and test the '$TRAVIS_BRANCH' branch for Kitura."
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./Kitura-CI/run_kitura_ubuntu_container.sh $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./Kitura-CI/build_kitura_package.sh ; fi
  - echo ">> Build and tests completed. See above for status."
